@baseUrl = http://localhost/desarrollo-curso/DWES-UD/mvcrecuperacion
//@auth basic apiclinica clinicaapi


### LISTAR
GET {{baseUrl}}/api/personas
Authorization: Basic apiclinica/clinicaapi
Content-Type: application/json
Accept: application/json

###

### CREAR (POST)
POST {{baseUrl}}/api/personas
Authorization: Basic apiclinica/clinicaapi
Content-Type: application/json
Accept: application/json

{
  "id": "4",
  "nombre": "pepe",
  "apellidos": "lopez gomez",
  "telefono": "666000000",
  "email": "joselopezgomez1@correo.com"
}
### DELETE
DELETE {{baseUrl}}/api/mascotas/1
Authorization: Basic apiclinica/clinicaapi
Content-Type: application/json
Accept: application/json


