@baseUrl = http://localhost/desarrollo-curso/DWES-UD/UD6-DWES/mvccomposerapicar

### Listado
GET {{baseUrl}}/apiCar/cars
Accept: application/json

###

### Detalle
GET {{baseUrl}}/apiCar/car/1
Accept: application/json
